analytics_engineer_test:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: test_analytics_engineer
      schema: main
      schemas_and_paths:
        main: 'test_analytics_engineer.sqlite'
      schema_directory: '/'
    prod:
      type: sqlite
      threads: 1
      database: test_analytics_engineer
      schema: main
      schemas_and_paths:
        main: 'test_analytics_engineer.sqlite'
      schema_directory: '/'
  target: dev
