analytics_engineer_test:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: test_analytics_engineer
      schema: main
      schemas_and_paths:
        main: '/home/galvsoliveira/data-analytics-engineer-test/test_analytics_engineer.sqlite'
      schema_directory: '/home/galvsoliveira/data-analytics-engineer-test/'
    prod:
      type: sqlite
      threads: 1
      database: test_analytics_engineer
      schema: main
      schemas_and_paths:
        main: '/home/galvsoliveira/data-analytics-engineer-test/test_analytics_engineer.sqlite'
      schema_directory: '/home/galvsoliveira/data-analytics-engineer-test/'
  target: dev
