{%- set match_columns_by_type = {
    'integer': [
        'id',
        'country_id',
        'league_id',
        'stage',
        'match_api_id',
        'home_team_api_id',
        'away_team_api_id',
        'home_team_goal',
        'away_team_goal'],
    'real': [
        'home_player_X1',
        'home_player_X2',
        'home_player_X3',
        'home_player_X4',
        'home_player_X5',
        'home_player_X6',
        'home_player_X7',
        'home_player_X8',
        'home_player_X9',
        'home_player_X10',
        'home_player_X11',
        'away_player_X1',
        'away_player_X2',
        'away_player_X3',
        'away_player_X4',
        'away_player_X5',
        'away_player_X6',
        'away_player_X7',
        'away_player_X8',
        'away_player_X9',
        'away_player_X10',
        'away_player_X11',
        'home_player_Y1',
        'home_player_Y2',
        'home_player_Y3',
        'home_player_Y4',
        'home_player_Y5',
        'home_player_Y6',
        'home_player_Y7',
        'home_player_Y8',
        'home_player_Y9',
        'home_player_Y10',
        'home_player_Y11',
        'away_player_Y1',
        'away_player_Y2',
        'away_player_Y3',
        'away_player_Y4',
        'away_player_Y5',
        'away_player_Y6',
        'away_player_Y7',
        'away_player_Y8',
        'away_player_Y9',
        'away_player_Y10',
        'away_player_Y11',
        'home_player_1',
        'home_player_2',
        'home_player_3',
        'home_player_4',
        'home_player_5',
        'home_player_6',
        'home_player_7',
        'home_player_8',
        'home_player_9',
        'home_player_10',
        'home_player_11',
        'away_player_1',
        'away_player_2',
        'away_player_3',
        'away_player_4',
        'away_player_5',
        'away_player_6',
        'away_player_7',
        'away_player_8',
        'away_player_9',
        'away_player_10',
        'away_player_11',
        'B365H',
        'B365D',
        'B365A',
        'BWH',
        'BWD',
        'BWA',
        'IWH',
        'IWD',
        'IWA',
        'LBH',
        'LBD',
        'LBA',
        'PSH',
        'PSD',
        'PSA',
        'WHH',
        'WHD',
        'WHA',
        'SJH',
        'SJD',
        'SJA',
        'VCH',
        'VCD',
        'VCA',
        'GBH',
        'GBD',
        'GBA',
        'BSH',
        'BSD',
        'BSA',
    ],
    'text': [
        'season',
    ],
    'date': [
        'date',
    ],
    'bad_html_data': [
        'goal',
        'shoton',
        'shotoff',
        'card',
        'foulcommit',
        'cross',
        'corner',
        'possession',
    ]
} %}

SELECT
    home_team_api_id,
    away_team_api_id,
    match_api_id,
    CAST(DATE(date) AS TEXT) AS date
FROM {{ source('Fifadata','Match') }}
--where home_team_api_id in (9996,274581)
--where home_team_api_id in (8024, 8244)
WHERE home_team_api_id IN (8020, 8031)
ORDER BY date DESC
-- hypotesis false, the team_api_id doesn't seem to change at an specific time
